module.exports = [
  {
    image_id: 1,
    title: "Living",
    filename: "ad4t4t4.jpg",
    category: "AI Selfie",
    likes: 5,
    user_id: 2,
  },
  {
    image_id: 2,
    title: "Happiness",
    filename: "45874.jpg",
    category: "Self Portrait",
    likes: 5,
    user_id: 1,
  },
  {
    image_id: 3,
    title: "Ocean",
    filename: "455646.jpg",
    category: "Underwater",
    likes: 5,
    user_id: 3,
  },
  {
    image_id: 4,
    title: "Living",
    filename: "44444.jpg",
    category: "Phone Selfie",
    likes: 5,
    user_id: 1,
  },
  {
    image_id: 5,
    title: "Alive",
    filename: "55555.jpg",
    category: "Phone Selfie",
    likes: 5,
    user_id: 3,
  },
];
